services:
  - type: web
    name: budget-tracker
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn budget_tracker.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budgettrackerdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: WEB_CONCURRENCY
        value: 4