# Generated by Django 5.1.6 on 2025-05-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_expense_category_entry_delete_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='category',
            field=models.CharField(blank=True, choices=[('Food', 'Food'), ('Bill', 'Bill'), ('Travel', 'Travel'), ('Health', 'Health'), ('Personal', 'Personal'), ('Debt', 'Debt'), ('Miscellaneous', 'Miscellaneous')], default='', max_length=20),
        ),
    ]
